### ISSUE TITLE
Fix CSP Header Not Set

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#1091]
Set Content Security Policy (CSP) to web portal routes.

<img width="1680" alt="CSP" src="https://user-images.githubusercontent.com/23434972/219559264-6660e661-bef4-469c-bb77-09881c164b09.png">

**Comment by pravin-yipl** [comment]
@man-git007 
pushed to `1091-fix-csp-heder-not-set` branch

**Comment by pravin-yipl** [comment]
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-FHkCJ3qN8BFtPQrzqajoZuUpzCBNtCOR1bSbCjhnS24='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

![image](https://user-images.githubusercontent.com/103093168/232672304-1f864270-d49f-4d8f-b3a7-fdf4f7ee10a6.png)

**Comment by sriza** [comment]
Closed temporarily. Halted for now.
