### ISSUE TITLE
Activity List Dynamic

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#116]
**Tasks**
- [x] dynamic table
- [x] dynamic pagination
- [x] modal form 
- [x] spacing fixes
- [x] activity dropdown close

**Comment by praweshsth** [comment]
**Add activity form**
1. In the form, when the external link 'For more information' is clicked, open the link in another tab instead of same tab. 
2. Show the list of language list from here: https://docs.google.com/spreadsheets/d/1okv1yB6iIU0Uzf-qGxpphNhF8xctsMTYLPWdmOtryDE/edit#gid=1429184668
3. Use the text and links for hover over information for elements of activities from https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675 see the elements/attributes in the spreadsheet and use exact text and link 
4. If the activity identifier already exist in the system, show 'This activity-identifier already exists' instead of 'The selected activity identifier is invalid.'
5. Sometimes when the activity is created an error message shows up: '{"id":6,"identifier":{"activity_identifier":"rm-2022-01","iati_identifier_text":"NP-CRO-45995\/063\/064-rm-2022-01"},"other_identifier":null,"title":[{"narrative":"Road manufacturing - 01","language":"en"}],"description":null,"status":"draft","activity_date":null,"contact_info":null,"activity_scope":null,"participating_organization":null,"recipient_country":null,"recipient_region":null,"location":null,"sector":null,"country_budget_items":null,"humanitarian_scope":null,"policy_marker":null,"collaboration_type":null,"default_flow_type":null,"default_finance_type":null,"default_aid_type":null,"default_tied_status":null,"budget":null,"planned_disbursement":null,"capital_spend":null,"document_link":null,"related_activity":null,"legacy_data":null,"conditions":null,"org_id":3,"default_field_values":null,"is_published":false,"tag":null,"created_at":"2022-05-11T09:35:46.000000Z","updated_at":"2022-05-11T09:35:46.000000Z"}' But the activity is created if you refresh the page. 
6. Can not open the pages

**Comment by praweshsth** [comment]
@sriza 

1. In add activity modal, the link in the information of xml:lang for title narrative should be https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/title/narrative/
2. When the logo at the top is clicked, it goes nowhere, always take it to activity listing page when signed in.

**Comment by man-git007** [comment]
@sriza @SauravSilwal10 @praweshsth Can we close this issue?
