### ISSUE TITLE
xml formed by Publisher Tool

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1225]
Hi, I've had a query through from a publisher who has provided data and is getting an error thrown by Validator.

I've checked the screens that have been populated and all looks fine to me, so I'm not sure if the xml thats been created is the problem.

Can you check this activity - https://publisher.iatistandard.org/activity/3135

The publisher is Fe-male 

I think the issue lies in the Indicators / Periods data.

Thanks
Dave

**Comment by sriza** [comment]
@DaveEade49 
Hi David, 
We looked into the xml file that the user published and noticed that the error was caused in the following fields and due to following reasons:

**Element 'language': This element is not expected. Expected is ( category )** 
Line 234: The user left the category field empty in the document link of target subelement of period. This caused xml file to not include the category tag.

**Element 'document-date': This element is not expected. Expected is ( category ).** 
Line 324 and 413 : The user left category and language field empty in target document link.

During the generation of XML file we check the values present within each element/subelement or field. If all the values within the element/subelement are null, the tags corresponding to them are not included in the XML file. In such case, the generated XML won't align with the sequence as defined by [IATI Activity Schema](https://iatistandard.org/reference_downloads/203/schema/downloads/iati-activities-schema.xsd) and validation errors are thrown.

cc @praweshsth

**Comment by praweshsth** [comment]
discussed and completed
