### ISSUE TITLE
Dashboard - Number of Inactive Publishers

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1263]
Not sure whether the figure is wrong or the text - I presume that the 99 is the number of publishers who HAVE been active rather than HAVE NOT?

![image](https://github.com/younginnovations/iatipublisher/assets/110898894/9976b358-952f-468b-9bc4-fbb9e4a693e5)

**Comment by praweshsth** [comment]
Fixed. this will be deployed along with other changes in dashboard

**Comment by sriza** [comment]
Merged to main branch along with PR #1205 .

**Comment by DaveEade49** [comment]
@sriza - hi can you just confirm the logic here - is it logged into Publisher Tool?

**Comment by sriza** [comment]
@DaveEade49 
Hi David,
The number of inactive publishers shows the number of publishers who have not logged in to the publisher tool for the last six months.

The implementation for this is done based on the maximum date on which the user logged into the publisher tool.
For eg, if organization name `organizationA` has 3 users and their logged in date are as follows:
- user-1 : 4th Aug, 2023
- user-2 : 5th July, 2023
- user-3 : 9th Sept, 2022

We conclude that the latest date for publisher login for `organizationA` is 4th Aug, 2023. 
Now, if this latest date for publisher login lies before 6 months they are included in the list of organizations who have not logged in for last 6 months and their count is displayed as `List of publishers inactive (not logged in) since 6 months in IATI`.

Please note that proxy has no effect on latest date for publisher login.

**Comment by DaveEade49** [comment]
Thanks great - Thank You
