### ISSUE TITLE
Activity Download - csv option does not work

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1283]
as it says, the csv doesn't seem to trigger a download - I know the xls works fine, so perhaps it was intended to be removed?

Same happens with "download all" csv option.

**Comment by sarinasindurakar** [comment]
Could you please provide the name of the organization and the browser you used to download the csv?
Please also include the steps or video for replicating this issue.

**Comment by IsabelBirds** [comment]
Hi,
The publisher was London School of Hygiene and Tropical Medicine, browser was firefox. 

My process was:
* Use the tick box to select the SUCCEED IATI activity
* Click on the download button
* Click on Download CSV in the dropdown

Nothing happened, but when I clicked on the Download XLS option the "Preparing activities for download" pop up appeared and I was able to download the XLS version of the files.

**Comment by PG-Momik** [comment]
Hi @IsabelBirds, here the summary of this issue.
# Issues
Couldn't download CSV for some organisations (London School of Hygiene and Tropical Medicine).

# Cause
The system uses 'publisher_id' from the Settings table when naming the CSV file. Since the organisation : London School of Hygiene and Tropical Medicine had not completely setup Settings, there didn't exist Settings or Settings >publisher_info > publisher_id. This meant that the system was trying to use null in the filename, causing the issue.

# Solution
We've made changes so that when naming the CSV file , 'publihser_id' from organisation > publisher_id is used.

---
We've deployed this fix to staging.

**Comment by praweshsth** [comment]
@IsabelBirds please check this in staging and inform us if this is good to go in production.
