### ISSUE TITLE
New Migration Request - Aidstream to IATI Publisher

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1284]
Bibliothèques Sans Frontières
id : bsf1

Please note organisation is already set up on Publisher.

Thanks
David

**Comment by Sanilblank** [comment]
For this organisations migration, we are facing an issue with the result codes (all results seem to have same code). The result codes are generated for each result so that they can be identified when uploading results via the xls feature. We are looking into this right now.
Also, after migration we faced some validation issues:

iatiidentifier:FR-INSEE-S499622017-Rapportannuel2021 
Recipient country :The Narrative field is required with @xml:lang field.
Activity Date:The Narrative field is required with @xml:lang field.
result:The vocabulary is already defined in its indicators
Actual Value:Value must be filled when the indicator measure is non-qualitative.
Result number is shown same in the all the result.

What should we do about these @DaveEade49.

**Comment by DaveEade49** [comment]
iatiidentifier:FR-INSEE-S499622017-Rapportannuel2021
Recipient country :The Narrative field is required with @xml:lang field. - **Leave Lang Blank**
Activity Date:The Narrative field is required with @xml:lang field. - **Leave Lang Blank**
result:The vocabulary is already defined in its indicators **Leave result field blank**
Actual Value:Value must be filled when the indicator measure is non-qualitative. **Set Value to 1**
Result number is shown same in the all the result. - **sorry can you explain further? - if all result numbers are the same leave blank, or if they are required append each one with -1;-2;-3 etc

**Comment by Sanilblank** [comment]
@DaveEade49 The last one is a problem from our side so we will be fixing that. The other validation issues will be fixed as you suggested above.

**Comment by sriza** [comment]
@DaveEade49 
We were working on migrating `Bibliothèques Sans Frontières` to the IATI publisher production site. While we were doing so, we found that the publisher had registered themselves in IATI Publisher on 9th of August.

Would it be ok to migrate the organization as existing organization?

**Comment by DaveEade49** [comment]
@sriza - yes that is fine

**Comment by Sanilblank** [comment]
@DaveEade49 We have done the migration. Please have a look.

**Comment by DaveEade49** [comment]
all ok
