### ISSUE TITLE
Publisher "hanging" on specific activity.

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1292]
Hi, publisher Education Development Trust has tried to publish the activity: "Wasichana Wetu Wafaulu - Let Our Girls Succeed - Phase 2".

I've also tried, but it just seems to hang and does not proceed or give an error message.

Can you advise if it's still working or gets stopped?

**Comment by DaveEade49** [comment]
[erroredt.txt](https://github.com/younginnovations/iatipublisher/files/12407669/erroredt.txt)

This is the error I get when I try to download the XML - not sure if this is connected

**Comment by DaveEade49** [comment]
![image](https://github.com/younginnovations/iatipublisher/assets/110898894/76f5572d-3927-434d-baba-938bf7b59e73)

**Comment by DaveEade49** [comment]
just seen there are a couple of rogue transactions without any values that were uploaded via the xls - so it's sorted now, but the error message and the hanging were confusing.

**Comment by praweshsth** [comment]
@sriza 

Flow: Upload an activity with transactions without any values via XLS upload then try to publish. 

Need to find why it is hanging and where it is hanging. And provide feedback to user while publishing or stop the upload in such case if necessary.

**Comment by sriza** [comment]
Hi @DaveEade49,
We looked into the above mentioned issue and found the "hanging" to be caused by timeout during validation of activity. Since validating activity is a foreground task, it can be carried out for maximum of 120 second only. If the task doesn't complete within this time limit, it causes the user interface to be stuck at "almost there" loader screen.

We have had previous discussion about treating the validation of activity as background task in the issue #1269 and are currently working on finalizing the design changes related to this issue. We will be solving this issue within #1269 itself.

Thank you

**Comment by DaveEade49** [comment]
ok thanks
