### ISSUE TITLE
Activities hanging when republished

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1299]
I'm creating a new issue for republishing problems that publisher "DanChurchAid" are experiencing, as it may be unrelated to validation timeout (#1269 )

DanChurchAid have 650+ activities, originally uploaded to Publisher via XML. Now, when they make small changes to an activity **within Publisher** and click "republish", the activity passes validation but hangs on the final publishing step (screenshots below).

Despite this, the IATI Registry seems to update with the changes. However the activity remains in "Draft" state in Publisher. Can we investigate why this is happening?

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/3a5ce5a1-1b2d-42d7-a917-e476fceb70b7)

**Comment by sarinasindurakar** [comment]
- [ ] When a user tries to unpublish an activity, it is stuck in the Almost there  and displays a gateway time out error. However, the activity is already unpublished when the user tries to unpublish it again. It displays the message as " The activity has not been published to unpublish".

https://github.com/younginnovations/iatipublisher/assets/65848732/577c5ed3-b61d-44e6-a890-4974f19a489e

**Comment by PG-Momik** [comment]
@emmajclegg this issue is related to, and under discussion in issue: #1269  , heres the summary:

### Issue

Given huge number of activities in an organization, functionalities : publish, unpublish and republish fail to  properly be completed in both single or bulk.

---

### Cause

-  In the current implementation, the system maintains a merged/master xml of activities published. However, changes are not made directly to the master xml; meaning when an activitiy(s) is published,  the activity is not directly appended to the merged xml but instead the merged activity is regenerated entirely.  Similarly incase of unpublish or republish, the merge file itself is regenerated. This process can be time consuming based on the number of already published activities.
     
    Likewise for bulk publish, this process is looped for each activity when bulk publish/republish is performed. 

    Given the number of activities being published alongside the activities that were already published, the execution time would increase and in some case even exhaust memory resources (resulting in a 504: Gateway timeout error, causing the process and the system to stop).

-  Other reason why activities hang when publish/republish can be because of how IATI Validator Response is being handle. This  problem is discussed in the issue: #1312 

---
### Proposed solution

Instead of regenerating the master xml each time an activity is published, unpublished or republished. We can:
- Create a master xml when an organisation publishes its first ever activity.
- In every subsequent publish, unpublish and republish, changes to the master xml would be made instead of  regenerating the master xml entirely.

| Action | Flow |
|---|---|
|Publish| Append activity to master xml|
|Unpublish| Remove activity from master xml|
|Republish| Remove existing acitivty xml from master xml -> Append activity to master xml|

---

Further details of of this can be found in issue: #1269.
The changes for this issue and issue: #1269 are(will) implemented in PR: #1300
