### ISSUE TITLE
Activity single/bulk publish in background process

### ISSUE THREAD

**Issue by rajkarnikar11** [younginnovations/iatipublisher#1311]

**Comment by A4family** [comment]
This addresses both Issue #1299 and #1269, which are interconnected problems.

**Issue:**

In the past, there were two methods for publishing activity files: individually or in bulk. When publishing an individual activity, all the steps occurred in the foreground, requiring users to wait for several seconds or even minutes for the publication to complete. On the other hand, when publishing activities in bulk, except for the validation step, the publishing process occurred in the background. This allowed users the freedom to navigate to other pages while the publishing process continued to run.

However,  the problem here is, even for the individual process, if the activity has a lots of content or the organization had already published hundreds of activities the process was unacceptably slow because of the validator and XML manipulation factor. 

**Solutions**

In case of activity validation, the issue causes and its solution is mentioned here. #1312

And, for the publishing / republishing issues  causes and solutions, it is mentioned here  #1269 which also covers up #1299

**Comment by sarinasindurakar** [comment]
- [ ]  Gateway time out error is shown while unpublishing the activity.
[Untitled_ Nov 06,2023 11_01 AM.webm](https://github.com/younginnovations/iatipublisher/assets/65848732/bc550e57-8279-4369-b383-4383c9059ccf)

- [ ] The previous publish is ongoing popup appears even when there isn't any current publishing.
[Untitled_ Nov 06,2023 11_21 AM.webm](https://github.com/younginnovations/iatipublisher/assets/65848732/fd5551f3-4396-4f2a-8710-c5f7bb041eeb)

- [ ]  The publishing data status is only displayed in background process section after the refreshing the page.
[Untitled_ Nov 06,2023 11_27 AM.webm](https://github.com/younginnovations/iatipublisher/assets/65848732/13d9c84d-f81b-4aed-aff6-d181e44a014a)

- [ ] The background tasks  section should be scrollable.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/e44951b8-9702-4bee-8b77-e15452c3f148)


- [ ]  Even if all background processes are terminated, the background process section and count remain visible.
