### ISSUE TITLE
Update core activity elements to reflect changes to default values

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1401]
Following changes made to default values in #1371, can we update the "core" activity data elements to make sure these align with recommended defaults?

This means removing _collaboration-type_ from core elements, and replacing it with _default-tied-status_

 
![image](https://github.com/younginnovations/iatipublisher/assets/137316374/661ac8eb-324c-499a-a8f2-1060485f6889)

**Comment by emmajclegg** [comment]
Estimated approx. 1.6 days - @praweshsth can we add more detail here on what's involved for my understanding?

Ideally, we want to make it as easy as possible to review and potentially update these "core" values again in future (if needed).

**Comment by PG-Momik** [comment]
@emmajclegg 
Currently, core elements list are hard coded into functions rather than being read from a single source. So we need to change multiple places  (2 - 3  functions within the code) where core elements are used. Making this change is not a big deal, but the effects of said changes needs to be tested. This is because almost all the workflow/modules (publish, import, creation, edit,) will be affected in some way.  So the subtasks in this issue will be something like this:

- Firstly we'll need to update the existing unit test to make sure that they are reliable and all the modules are  working as intended.
- Second, we'll need to work on a script that updates `complete_percentage` value of all activities in the system.
- Finally the QA will need to go through all the workflows and make sure that the changes and the script are working as expected.

> Ideally, we want to make it as easy as possible to review and potentially update these "core" values again in future (if needed).

Yes, we thought the same as well, so we'll be rewriting the modules for how core elements are maintained.

**Comment by emmajclegg** [comment]
Ok, thanks @PG-Momik. Yes - it makes sense to put the time in now to remove dependency on hard-coding in that case.

**Comment by PG-Momik** [comment]
@emmajclegg  this has been deployed to staging. 
Activities will now consider `default_tied_status` as core element instead of `collaboration_type`. Old activity data have been updated as well.

**Comment by emmajclegg** [comment]
Great - all looks good to me @PG-Momik

**Comment by PG-Momik** [comment]
This has been deployed to production.
