### ISSUE TITLE
Simplify activity recipient-country data entry screen

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1410]
When completing `recipient-country` within an activity, only the `code` element is marked as mandatory:
![image](https://github.com/younginnovations/iatipublisher/assets/137316374/8eb64e48-eb8a-4409-87b9-c543477e65db)

However, if the user populates `code` alone, `recipient-country` is marked as "not completed":
<img width="361" alt="image" src="https://github.com/younginnovations/iatipublisher/assets/137316374/385032b0-941c-400a-9557-2184056fec43">

The user has to go back and populate `percentage` to turn the status to "completed":
<img width="368" alt="image" src="https://github.com/younginnovations/iatipublisher/assets/137316374/0979b200-1743-4a01-b4e9-f96cfca2309d">

1. Can we show `percentage` with a mandatory asterisk so it is clearer to the user that this needs populating?
2. Can the sub-element `narrative` section (highlighted below) be hidden within an expandable section?
 
Reason: [recipient-country narrative](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/recipient-country/narrative/) is a rarely used sub-element that clutters the interface and risks being populated in error. I'm considering how we make data entry look simpler across the tool - users that need this section could click an ”Add narrative" button to expand for example.

<img width="908" alt="image" src="https://github.com/younginnovations/iatipublisher/assets/137316374/21dfb855-0f68-42a9-a6b4-23eb3b1ec928">

**Comment by praweshsth** [comment]
# Issue/ concern/ question

- The completeness of Recipient Country (RC) and Recipient Region (RR) are tied with the percentage. 
- Possible combination of percentages for completeness are: RC=100% or RR=100% or RC+RR=100% or RC1+RC2...+RCn=100% or RR1+RR2+...+RRn=100% or RC1+RC2+...+RR1+RR2+...=100%
- Given this condition, if percentage is made mandatory, if user adds percentage which is less than 100, both RR and RC will not be marked as completed and the user will be confused about it. 
- We think, percentage should not be made mandatory but there should be a better way to inform the user regarding this condition. 

@emmajclegg

**Comment by emmajclegg** [comment]
Perhaps we can add the mandatory field red asterisk next to "percentage" in the user interface, but not make any underlying coding changes? So this informs the user that they need to populate percentage but doesn't affect the way the completeness alert currently works.

**Comment by praweshsth** [comment]
@emmajclegg 

The red asterisk is part of a reused code, which is implied for the fields marked as mandatory. We don't suggest to do as you have suggested because it will prevent us from having a cleaner code as the mandatory functionality should be consistent everywhere and this could change that. Instead, we can make it mandatory and as mentioned before, this might be confusing for users when the RC or RR are not marked as complete even though the percentage has been added.

**Comment by emmajclegg** [comment]
@praweshsth  - we agree with your comment below:
>We think, percentage should not be made mandatory but there should be a better way to inform the user regarding this condition.

As far as I can see IATI Publisher is applying the rules around `recipient-country` and `recipient-region` correctly in its underlying code, as per the IATI Standard. This issue is more related to the user experience of the data completeness alert in the situation I've described above (my example screenshots show `recipient-country `data entry, but the same will apply if the user is populating `recipient-region` instead).

The user completes country `code`, sees the sections as "not completed", then has to figure out through trial and error that missing `percentage` is the reason for this.

If you and the team share some ideas on how we could improve the user messaging, we'll happily comment from there?

**Comment by praweshsth** [comment]
@emmajclegg 

Both Recipient Country and Recipient Regions have 'Help' link, when clicked shows the message about it. Check the images below:

![Image](https://github.com/younginnovations/iatipublisher/assets/2421695/17f0d442-20fa-4e58-8119-a0a07afae280)
![Image](https://github.com/younginnovations/iatipublisher/assets/2421695/f2d1979e-5462-4e51-baf8-1e7e5cd524c9)

We can Remove that 'Help' links and always display the messages. So that user can see it all the time. That messaging should be more clear about the rule and how they can make it complete. This message should also include about transaction level. 

Please refer to guidance for this in IATI standard - https://iatistandard.org/en/guidance/standard-guidance/countries-regions/ to prepare the messaging.
