### ISSUE TITLE
Difference in  publisher-type codelist present in our system and IATI registry.

### ISSUE THREAD

**Issue by sarinasindurakar** [younginnovations/iatipublisher#1417]
While registering the new organization, I noticed that the publisher type was not selected in the IATI registry, despite being filled/selected during organization creation in the system. Upon further testing, I found out that some publisher-type codes available in our system were missing from the IATI registry.

The available publisher type code list in our system is as follows:

- Government
- Local Government
- Other Public Sector
- International NGO
- National NGO
- Regional NGO
- Partner Country based NGO
- Public Private Partnership
- Multilateral
- Foundation
- Private Sector
- Private Sector in Provider Country
- Private Sector in Aid Recipient Country
- Private Sector in Third Country
- Academic, Training and Research
- Other

The available publisher-type code list in the IATI registry is as follows:
- Academic, Training and Research
- Foundation
- Government
- Dedication
- International NGO
- Multilateral
- National NGO
- Other Public Sector
- Private Sector
- Public Private Partnership
- Regional NGO

@emmajclegg 
 Have some publisher types been deprecated from IATI standard? If so could you let us know of other similar changes?

**Comment by emmajclegg** [comment]
Thanks for flagging @sarinasindurakar - I'm checking within the team to establish which is the most up to date list.

**Comment by stevieflow** [comment]
> The available publisher type code list in our system is as follows:
> 
>     * Government
> 
>     * Local Government
> 
>     * Other Public Sector
> 
>     * International NGO
> 
>     * National NGO
> 
>     * Regional NGO
> 
>     * Partner Country based NGO
> 
>     * Public Private Partnership
> 
>     * Multilateral
> 
>     * Foundation
> 
>     * Private Sector
> 
>     * Private Sector in Provider Country
> 
>     * Private Sector in Aid Recipient Country
> 
>     * Private Sector in Third Country
> 
>     * Academic, Training and Research
> 
>     * Other

This aligns with the [Organisation Type](https://iatistandard.org/en/iati-standard/203/codelists/organisationtype/) codelist in the standard

Two things:

- There's no concept of "publisher" specifically in the standard - but agree it's confusing (the closest the standard has is [reporting-org](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/reporting-org/), which does have the type attribute ^
- I suspect that the IATI Registry list for "publisher type" started out as being the same as the IATI standard codelist, but has fallen out of synch [six years ago, when that list was updated]([url](https://github.com/IATI/IATI-Codelists/issues/113)) with new values

**Comment by emmajclegg** [comment]
Thanks @stevieflow.  @sarinasindurakar - this means IATI Publisher is using the correct codelist and it's the IATI Registry that's out of date. We'll note this as an action for the Registry but, unless it's actively causing problems for Publisher, we won't treat it as urgent. We're aware data collection at point of registration needs reviewing for the Registry.

Whilst IATI Publisher's codelist is correct, this would be a good opportunity to rename the dropdown in the interface to "Organisation Type" rather than "Publisher Type". Both terms are currently referred to in the interface guidance, and Organisation Type is the correct name for the codelist:

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/25cf0544-eab7-4433-a7d6-9e58bea19608)

(we're aware that the Registry also needs this correction)
