### ISSUE TITLE
Unable to re-add a user to IATI Publisher after deletion

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1419]
An organisation has contacted IATI Support about being unable to re-add a user account to IATI Publisher that they previously deleted (Zendesk support ticket: #[44090](https://iati.zendesk.com/agent/tickets/44090)). Their email address is flagged "as already in use" despite the user account no longer appearing in IATI Publisher's user list.

I have recreated the issue as follows:

1) While logged in as an Admin user of the organisation "Emma's test publisher" in IATI Publisher staging, I go to the [Users](https://iatipublisher-staging.yipl.com.np/users) page and add a new user with email address emma.clegg+test1419@opendataservices.coop :

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/ff9b8469-b85c-48e5-adbd-b632a96c3cb7)

2) I see the new user on my organisation's Users page:
![image](https://github.com/younginnovations/iatipublisher/assets/137316374/5c6e1144-c593-4e10-8cad-89d3f1d66042)

3) I delete the user I've just created from the Users page. I do not check the box "Mark as spam":
![image](https://github.com/younginnovations/iatipublisher/assets/137316374/7073d98f-8e17-45e5-98a5-12fcded61a61)

The user is successfully deleted (according to a pop up message) and no longer appear in my organisation's Users list. 

4) If I then try to re-add the user by clicking "Add a new user", via the button on the Users page, I get an error message saying the email has already been taken:
![image](https://github.com/younginnovations/iatipublisher/assets/137316374/0af64489-5ee4-4438-9606-e6876ddbfe73)

Questions: 
- What's causing IATI Publisher to remember the email address after deletion? (we don't want an email address blocked from re-registering in this case)
- Is there any link with user accounts on the IATI Registry in this process? (I couldn't find this user account on IATI Registry staging so don't think this is the issue)

**Comment by praweshsth** [comment]
> What's causing IATI Publisher to remember the email address after deletion? (we don't want an email address blocked from re-registering in this case)

Soft delete of the user is causing this. We can't find out why this feature was implemented instead of permanent delete. 

> Is there any link with user accounts on the IATI Registry in this process? (I couldn't find this user account on IATI Registry staging so don't think this is the issue)
No

**Comment by emmajclegg** [comment]
ok thanks @praweshsth. I've removed the priority label from this issue as it's not immediately affecting any more users.

It sounds like a hard delete would make sense to introduce here, if there was no other reason for the soft delete, as I see no reason to block users from reregistering with their email address. I'll leave this issue open as a proposed task, ready for estimation.

**Comment by PG-Momik** [comment]
@emmajclegg We can add hard delete for users. 

## Concern
Given that an organization has only 1 admin user, this user cannot be deleted, even by the superadmin. This is because the 'Proxy' feature requires an orgnization to have atleast 1 admin user associated to the organisation.

## Proposed workflow for the mentioned concern 
To delete the last admin user of an organisation, a new admin user would need to be added from the users listing page, then proceed to delete the admin user .

## Task
- [ ] Remove soft delete from users

## Subtask
The system currently keeps a log of some actions performed by any user, however only user id is tracked. Given that we will be implementing hard delete, tracking user id will be of no use. We've decided to track fullname and email as well.

- [ ] Record fullname and email of user in activity log

**Comment by praweshsth** [comment]
estimation added.

**Comment by PG-Momik** [comment]
This has been deployed to staging.

**Comment by emmajclegg** [comment]
Great, thanks - all looks to be working as expected.
