### ISSUE TITLE
Publishing steps and progress are unclear to users through the Background Tasks box

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1423]
Users are confused by the Background Tasks box when publishing activities in IATI Publisher, often not knowing whether action is required of them or not.

For example,
1) Users do not realise that they need to click "Proceed" in the Background Tasks box, after validation, to complete publication of activities:

<img width="1411" alt="image" src="https://github.com/younginnovations/iatipublisher/assets/137316374/a15baae0-9f49-45ae-9e0f-b2d88243b60e">

2) The Background Tasks box remains on screen even after successful task completion. Users are left unsure whether there are tasks still running or not:

<img width="1416" alt="image" src="https://github.com/younginnovations/iatipublisher/assets/137316374/82c64a8a-97ec-4769-b417-d311ed076195">

Can we think of a more visible way to guide users through the steps to publishing, e.g. with a progress bar or [Wizard steps](https://www.google.co.uk/search?sca_esv=3acf9be9fedf7d41&sca_upv=1&q=dribbble+wizard+steps&uds=AMwkrPvl542ijrccCKFlvcOh2QJPKuPs6t7LczJdJ6Cy9E7wId8znAnU1phbgAYikKwSrJY4i1QkWyZcD77YwWydfZ1s9-DJE16d2Hlo1E0kS92Yw7J9mtxOiShgaNzIu0bAAu30zgqJky6Dy5Il9LmE24jnDLaV2knc-RtBHTpWKMC0twZNBop23j6IuBK2_LavyjZ9jDNj0KIJadD1lbJtVgRtfRgleP_PDEiwhRadAm0VEOyM_V8NvYt3M9ccChnVr8aDWFJ9IOBzpWfc5rnqBWY6baVuw7PFm2Sgp1ZCTiyJlWcLQApSvmTml9SOBbj_Fiyre9xw&udm=2&prmd=ivnmbtz&sa=X&ved=2ahUKEwjN8Pr67LKFAxXuWUEAHZGaCLIQtKgLegQIDBAB&biw=1920&bih=1087&dpr=1)? So that they know what they have completed and which steps remain (Core Value check >> Validation >> Publish)

At minimum, the "Continue to publish" action (currently labelled "Proceed") needs to be centre screen so that it is not missed by users. Also, the "Background Tasks" box should not remain on screen when publication has successfully completed. We've had a suggestion that a "Tasks" tab (i.e. a new page in the interface) may work better than a pop-up box, but let us know what you think based on the above user feedback.

**Comment by praweshsth** [comment]
@emmajclegg This mean that we need to fix the UX. And we need to make change in the flow design and then work on it. What do you think?

**Comment by emmajclegg** [comment]
@praweshsth - if you can propose some ideas for changes to the user interface, I would be happy to discuss them (before the next fortnightly call if useful). Any screenshots would make it easier to comment - e.g we were looking at these [wizard examples](https://www.google.co.uk/search?sca_esv=3acf9be9fedf7d41&sca_upv=1&q=dribbble+wizard+steps&uds=AMwkrPvl542ijrccCKFlvcOh2QJPKuPs6t7LczJdJ6Cy9E7wId8znAnU1phbgAYikKwSrJY4i1QkWyZcD77YwWydfZ1s9-DJE16d2Hlo1E0kS92Yw7J9mtxOiShgaNzIu0bAAu30zgqJky6Dy5Il9LmE24jnDLaV2knc-RtBHTpWKMC0twZNBop23j6IuBK2_LavyjZ9jDNj0KIJadD1lbJtVgRtfRgleP_PDEiwhRadAm0VEOyM_V8NvYt3M9ccChnVr8aDWFJ9IOBzpWfc5rnqBWY6baVuw7PFm2Sgp1ZCTiyJlWcLQApSvmTml9SOBbj_Fiyre9xw&udm=2&prmd=ivnmbtz&sa=X&ved=2ahUKEwjN8Pr67LKFAxXuWUEAHZGaCLIQtKgLegQIDBAB&biw=1920&bih=1087&dpr=1#vhid=Igd8Rv_Qlng26M&vssid=mosaic) yesterday for inspiration.

**Comment by praweshsth** [comment]
@emmajclegg 

Since this is UX issue, we should go ahead with designing the UX for it. Based on that only, we can do an estimation for development. So will it be ok to put an estimation for design first and work on it and come back and put estimation for development?

**Comment by emmajclegg** [comment]
@praweshsth - yes sure, go ahead and estimate work for the design step

**Comment by emmajclegg** [comment]
I'm moving this to "to do" based on the estimation for design work. Happy to discuss on our call tomorrow @praweshsth

**Comment by shreyaydi** [comment]
We have worked on the flow of publishing. We felt that the users weren't made aware enough of what was going on while the process took place. So, we've tried to address the problem here. Please have a look at the flow and we've also added a video of how the interaction in the flow looks like. 

[Figma Prototype](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=9481%3A163952&node-id=14335-57171&starting-point-node-id=14335%3A57171&scaling=scale-down&mode=design&t=oVHSH1jZyrC5V4Fq-1)



https://github.com/younginnovations/iatipublisher/assets/47111065/06dc0180-e264-40ef-9d79-5e6b9f3efaed

**Comment by emmajclegg** [comment]
Thanks @shreyaydi - this is looking really good! That's much clearer what's going on.

A few comments, which I'm happy to discuss with @praweshsth on the call tomorrow:

- To reduce the number of steps in the workflow, could the core elements and deprecated code check (steps 1 & 2) be combined so that the user gets feedback for both together? Whilst it's good that deprecated codes are checked as per [#1407](https://github.com/younginnovations/iatipublisher/issues/1407), I think this - i.e. Step 2 - can happen in the background without the user needing to see it explicitly as a step. 
- "Continue" is a more commonly used word than "Proceed" for the forward action buttons 
- It looks like the "Ongoing Tasks" bar flashes slightly when the box has been minimised and an action completes? If so, making this even more obvious to users would be good so there's no chance of people missing it.

![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/f84d92d7-a80a-4e2f-9fdb-fd54de66ffc1)

**Questions**
-  If no issues are found for steps 1 & 2 (i.e. core elements are complete and deprecated codes have not been used), does step 3 (validation) automatically start? I think it should, to minimise the number of times the user has to click.
- If issues are found, does clicking one of the arrows in the screenshot below take the user to that activity's overview screen? 

![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/585bed17-6d1d-4ee6-abec-104df9308346)

**Comment by shreyaydi** [comment]
We've updated the flow according to the discussion we had in the last meeting, please have a look at the prototypes linked in this issue. The first link is for the flow with incomplete core elements and deprecated codes and the second one is without them. 

If you face difficulties or don't know where to click, you could simply use the arrow buttons on your keyboard to navigate through the flow design.

If there are any comments on the flow, please let us know or post a comment by pressing the "c" button,

[Bulk publish 1](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?type=design&node-id=9481-163952&viewport=-67610%2C-55585%2C1.37&t=EA4SYH5elL0ao097-0&scaling=scale-down&starting-point-node-id=14371%3A32295&show-proto-sidebar=1)

[Bulk Publish 2](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?type=design&node-id=9481-163952&viewport=-67610%2C-55585%2C1.37&t=EA4SYH5elL0ao097-0&scaling=scale-down&starting-point-node-id=14372%3A39831&show-proto-sidebar=1)

**Comment by emmajclegg** [comment]
Thanks both - this is looking good. Let me show this to the wider support team tomorrow and I will get back to you with any comments we have.

**Comment by shreyaydi** [comment]
We've worked on the flow by reducing the process to a two step process. Please have a look at these 4 prototypes here:
[1. Bulk Publish flow](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?node-id=9481-163952&viewport=-27564%2C-25424%2C0.55&t=J5SjYA5kEiHqFagD-0&scaling=scale-down&starting-point-node-id=14428%3A38969&show-proto-sidebar=1)
This is a basic flow of how our import will look

[2. Bulk publish with no issues encountered](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?node-id=9481-163952&viewport=-27564%2C-25424%2C0.55&t=J5SjYA5kEiHqFagD-0&scaling=scale-down&starting-point-node-id=14428%3A38986&show-proto-sidebar=1)
This is a flow if there are no issues found in any steps and the publish finishes in one go. (the user doesn't minimize the popup)

[3. Bulk Publish with no issue encountered and user minimizes the popup](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?node-id=9481-163952&viewport=-27564%2C-25424%2C0.55&t=J5SjYA5kEiHqFagD-0&scaling=scale-down&starting-point-node-id=14443%3A35536&show-proto-sidebar=1)
Since we do all the needed checks in Step 1, we think users should have the choice to make pop-up notifications smaller right from the beginning. In this way, users can make the pop-ups smaller during the first step and finish publishing without any interruptions. They'll only see the blinks after publishing is done.

[4. Bulk publish with issues encountered in each step and user minimizes the popup](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?node-id=9481-163952&viewport=-27564%2C-25424%2C0.55&t=J5SjYA5kEiHqFagD-0&scaling=scale-down&starting-point-node-id=14443%3A38061&show-proto-sidebar=1)
This flow is basically what happens when the user minimizes the pop up and issues are encountered in each step.

I have also addressed the [Figma comment](https://www.figma.com/design/upgUy5i65LYC3iiqYVnACW?node-id=14371-32441#799772757)

Please have a look at it and let us know if there are any confusions

**Comment by shreyaydi** [comment]
@emmajclegg I have updated the texts on the flow as per your suggestions, and for the tab, I've replied on the comment as well, the tab with no results will be hidden.

cc @praweshsth

**Comment by emmajclegg** [comment]
@praweshsth - let me know when you've had a chance to estimate development effort for this as a team, then I'll move it to "to do"

This issue remains higher priority than #[1439](https://github.com/younginnovations/iatipublisher/issues/1439) as it's affecting more end users and generating more support queries.

**Comment by emmajclegg** [comment]
@praweshsth - has there been progress on getting the development-side of this work estimated? Thanks

**Comment by praweshsth** [comment]
@emmajclegg shall we start work on this?

**Comment by emmajclegg** [comment]
@praweshsth - I haven't had a chance to discuss with the wider IATI Support team yet, so let me do that tomorrow and I will confirm here after. This relates to us deciding what improvements are definitely worth doing in the next few months, given recent discussions about AidStream and Publisher.

**Comment by emmajclegg** [comment]
Go ahead with the development work on this @praweshsth . We think the new publishing workflow will help a lot of users, even in the short term.

**Comment by sarinasindurakar** [comment]
@Sanjivchy 
 Fix these issues.

- [ ] 1.  Even if activity is already published, the user  is redirected to core element section.
https://github.com/user-attachments/assets/9556e11a-43ba-4d2c-9fe8-1d2477d1d709

- [ ] 2. When the user cancels the publishing process, the previous buttons are displayed, and only the modal is closed. This is quite confusing.


https://github.com/user-attachments/assets/88c32b8d-674f-4e0d-b4c5-5e8a988ed960

- [ ]  3.  The count of activities are not shown in core element tab and deprecated tab.


![Image](https://github.com/user-attachments/assets/dfd857f8-4317-4cd3-9c05-6d7041ee1fc2)

- [ ]  4.   When the user cancels the bulk publish process, the process is not actually canceled, and the activities are already being published.

**Comment by subash-cm** [comment]
@Sanjivchy 

- [ ] 1. Before publishing, change Button label to "CONTINUE PUBLISHING" as per figma design and count should be equal to the selected Activity

![image](https://github.com/user-attachments/assets/b661148c-e454-4439-a0d1-fdf0cbfa3fc0)


- [ ] 2. On minimized state, While checking for data to be published, do not show validation error until status is completed


https://github.com/user-attachments/assets/f974e574-2fe9-476e-8624-74f9cacbf143

**Comment by emmajclegg** [comment]
This is looking really great guys! Everything looks to be working as expected - my one comment is can we get rid of the "Publishing alert" that appears when a user first clicks to publish an activity? :

![image](https://github.com/user-attachments/assets/412c6637-d4c1-42f6-ab04-82e1ec7e0f4d)

I don't see it as necessary - it's intuitive from the activity overview screen what's being published for the first time vs. republished, and the language in this message is confusing. Removing it would streamline the process further and mean one less click for the user.

**Comment by praweshsth** [comment]
@emmajclegg we have made the changes as per your feedback. Please review it.

**Comment by emmajclegg** [comment]
thanks @praweshsth - all looks good!

**Comment by PG-Momik** [comment]
@Sanjivchy @subash-cm Moving this to Todo, xls import not working on this change.

**Comment by PG-Momik** [comment]
Closing this issue. Has been deployed to production with necessary fixes. 

> [!NOTE]
> Please open another issue if any bugs related to this are discovered in prod.
