### ISSUE TITLE
Organisation dataset being deleted by archiver when organisation dataset is published after unpublishing it

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1433]
# Issue

The archiver of IATI Registry is deleting the organisation dataset after the organisation file is unpublished and then published again. In case of republishing, the dataset is not deleted by the archiver. 

# Possible Reason
When an organisation dataset is unpulished, package_delete endpoint is used to remove the dataset. After that when the organisation file is published again, package_create endpoint comes into action. But when organisation file is republished after editing, package_update endpoint is used. May be because of this difference the archiver is deleting the organisation file. 

# How activity unpublish and repulish is handled?
When activity file is unpublished, package_update endpoint is used to link an empty xml file instead of using package_delete endpoint. Same thing for activity republishing. Hence there is no issue in case of activity file. 

# Trying Purge
We went through CKAN API docs and tried to use the endpoint to purge on deletion. But the endpoint to purge doesn't exist in IATI Registry. 

# Possible solution
Similar to Activity file, we can just update the organisation xml to an empty xml,  without removing the dataset file from registry.

**Comment by robredpath** [comment]
After our conversation yesterday, I wanted to record here that I suggested a possible workaround. 

I think that if you supply a different `name` when calling `package_create` then it will avoid the deletion problem, because the archiver will see it as a different dataset. 

This could be a version number, or a random string appended to the end of the dataset name, for example.

**Comment by praweshsth** [comment]
@emmajclegg we think this issue is also present in production of IATI Registry. Recently, we found that the archiver deleted the activity file while testing in AidStream.

**Comment by emmajclegg** [comment]
Thanks @praweshsth - we're still troubleshooting this with our third-party supplier for the IATI Registry and will update here as soon as possible. 

When you say the issue is also present in the production Registry site, was AidStream testing directly on the production site when the activity file issue was spotted? If you have an example of a publisher affected on the live site, let me know by email and I'll add it to the troubleshooting log.

**Comment by PG-Momik** [comment]
After going through [dataset_purge (maybe) doesn't exist in IATI Registry API](https://github.com/IATI/ckanext-iati/issues/454). Purging the dataset seems to be working,  instead of versioning we can just purge the organisation dataset when an organisation Unpublishes the organisation dataset.

**Comment by sarinasindurakar** [comment]
Hi @emmajclegg,
I haven't been able to recreate the issue with dataset deletion in the IATI registry. If it happens again, I'll let you know right away.

Previously, when I was publishing the activity of Younginnovation in Aidstream,  activity dataset which belong to India did not show up as  the dataset was deleted by  IATI Archiver.

![Image](https://github.com/younginnovations/iatipublisher/assets/65848732/a5a4af8c-a6c5-4f25-8168-1fb6f51e00b1)

**Comment by PG-Momik** [comment]
This has been deployed to staging. The testable for this issue was :
1. The organisation dataset should not disappear when : publish -> unpublish -> publish
