### ISSUE TITLE
Upload failed error when importing activity.xlsx file

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1525]
This affects one publisher with a large volume of activities - details can be found in this support ticket: https://iati.zendesk.com/agent/tickets/44912

**Comment by PG-Momik** [comment]
@emmajclegg  I've looked into this. 

> ...They have a lot of activities (876), which I think is causing problems.
> zendesk ticket

Yes, as you suspected, the large number of activities and transactions is causing the import to fail. The queue job times out due to the volume of data. We can work around this by :
1. Importing the activities in a batch of 100 to 200 based on the number of transaction an activity has, or
2. Look into increasing queue timeout

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - I've suggested an easier fix for this specific case in the Zendesk ticket: https://iati.zendesk.com/agent/tickets/44912

It's useful to be aware of the IATI Publisher import limits though, particularly in the context of moving AidStream users across eventually who may have similar amounts of data.

**Comment by PG-Momik** [comment]
@emmajclegg Changes have been made per discussions on zendesk. Please close this issue if everything is okay.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - the changes all look good to me. I've let the publisher know and will close this issue next week if they come back with no questions.

**Comment by emmajclegg** [comment]
Closing as issue resolved
