### ISSUE TITLE
Create designs for revised workflow of .xls import 

### ISSUE THREAD

**Issue by BibhaT** [younginnovations/iatipublisher#1537]
Initial issue: https://github.com/orgs/younginnovations/projects/3?pane=issue&itemId=61369915 

New workflow: [IATI Publisher Import Workflow.pdf](https://github.com/user-attachments/files/16637012/IATI.Publisher.Import.Workflow.pdf)

Explanatory video for the same: https://youtu.be/fbrz8th02so

Things to consider: (as commented by Emma in #1439 
For the download step - for info - I had already started thinking about how we simplify exporting data as a future improvement here: https://github.com/younginnovations/iatipublisher/issues/1526 (there are a lot of steps currently)

I'm happy to progress with this design, and happy to help with instruction text for the interface if you need. The main thing I think is important to make clear to users is when an import is about to overwrite existing data in IATI Publisher, which can be factored into the in-tool instructions at the "change data and upload" steps in the workflow.

**Comment by asminashrestha** [comment]
Hi, @emmajclegg 

We have created three variations of the revised workflow for the bulk import and within-activity import, each divided into four sections:
1. A section for users to choose the element to be imported
2. A section to select if the importing element exists or not
3. A section for the actual import process
4. A section to inform users about the download option available in our system

Variation 1: This variation features separate pages for each functionality, offering clear separation between steps.

Bulk Import:[ View Here](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=15482%3A30650&node-id=15489-48052&node-type=FRAME&viewport=1843%2C-3882%2C0.4&t=jtaSyBuoCZnN5ZPe-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=15489%3A48052&show-proto-sidebar=1)

Within Activity:[ View Here](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=15482%3A30650&node-id=15482-31574&node-type=FRAME&viewport=1843%2C-3882%2C0.4&t=jtaSyBuoCZnN5ZPe-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=15482%3A31574&show-proto-sidebar=1)

Variation 2: This variation focuses on distinct visual grouping of sections within the workflow, while maintaining a unified flow.

Bulk Import:[ View Here](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=15482%3A30650&node-id=15555-65806&node-type=FRAME&viewport=1843%2C-3882%2C0.4&t=jtaSyBuoCZnN5ZPe-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=15555%3A65806&show-proto-sidebar=1)

Within Activity:[ View Here](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=15482%3A30650&node-id=15555-66071&node-type=FRAME&viewport=1843%2C-3882%2C0.4&t=jtaSyBuoCZnN5ZPe-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=15555%3A66071&show-proto-sidebar=1)

Variation 3: This variation keeps all the functionalities on a single page, allowing users to complete the workflow without navigating through multiple pages.

Bulk Import:[ View Here](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=15482%3A30650&node-id=15555-67040&node-type=FRAME&viewport=1843%2C-3882%2C0.4&t=jtaSyBuoCZnN5ZPe-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=15555%3A67040&show-proto-sidebar=1)

Within Activity:[ View Here](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=15482%3A30650&node-id=15555-67735&node-type=FRAME&viewport=1843%2C-3882%2C0.4&t=jtaSyBuoCZnN5ZPe-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=15555%3A67735&show-proto-sidebar=1)

These screens are still a work in progress, and we would greatly appreciate your feedback.
Please take a look at these options and share your thoughts.

**Comment by emmajclegg** [comment]
Hi @asminashrestha - thanks for these, it's definitely useful to see options.

Variations 1 and 2 look more intuitive than 3 (where I think it's too complicated having all the steps on the same page)

My favourite is variation 1, as I think it's logical to read the steps left-to-right. That said, I think it makes sense to swap the "Upload your file" block with the "Templates" block, as the workflow would be: Choose an action >> Download template or existing data >> Upload your file , if I'm interpreting it correctly?

Under "Choose an Action", we'll need to make it clear that users can update existing data and add new data at the same time by selecting the "Update existing..." option, but we can include that in the subtext. 

I'm highlighting what I'm referring to here, in case it's not clear:

![Image](https://github.com/user-attachments/assets/cb36beb7-b911-4af9-8871-45a0de62194a)

Any questions - or different views - let me know.

**Comment by asminashrestha** [comment]
Thank you so much for your feedback! I completely see where you're coming from regarding the left-to-right flow. I’d like to clarify that our intention wasn’t to present these elements as sequential steps but rather as individual instances, each serving a distinct role in the workflow.
Additionally, in some cases, users might not always download and then upload—these actions can vary depending on their needs at the time.
With that in mind, we thought placing the main action at the center would create a more flexible and user-friendly experience.

**Comment by emmajclegg** [comment]
Ok, thanks for the thoughts @asminashrestha. 

A potential problem that comes to mind is users trying to upload a random data file (i.e. one not in the IATI Publisher template format), which I expect some people will do regardless of the guidance we provide. We sometimes see this in support queries. So I don't think it's a bad thing to make the template more obvious in a left-to-right flow.

I agree the upload feature is the main action and you've made this obvious from its size on screen.

**Comment by asminashrestha** [comment]
@emmajclegg Thanks for your feedback. As you suggested we have decided to move forward with the left-to-right approach for the design. While doing so, we also realized that the previous design didn’t make it clear that the section with download and upload options changes when the user clicks 'Add New' or 'Update Existing'. To resolve this, we’ve created an updated design that not only incorporates the left-to-right flow but also provides a more logical and intuitive user experience. 
Additionally, we have created a screen to handle the case where an activity has no results.

Here are the links:
Bulk Import: [View Link](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=15482%3A30650&node-id=15650-17961&node-type=FRAME&viewport=210%2C-4849%2C0.13&t=p6P1tYo0YgIizHo9-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=15650%3A17961&show-proto-sidebar=1)
Within Activity: [View Link](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=15482%3A30650&node-id=15650-17970&node-type=FRAME&viewport=210%2C-4849%2C0.13&t=p6P1tYo0YgIizHo9-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=15650%3A17970&show-proto-sidebar=1)
No Result Case: [View Link](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=15482%3A30650&node-id=15694-15385&node-type=FRAME&viewport=210%2C-4849%2C0.13&t=p6P1tYo0YgIizHo9-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=15694%3A15385&show-proto-sidebar=1)

**Comment by emmajclegg** [comment]
Hi @asminashrestha - ok thanks, I think this looks fine.

**Comment by praweshsth** [comment]
@emmajclegg please check the links above to see the full workflow design

**Comment by emmajclegg** [comment]
@praweshsth @asminashrestha - thanks.

I've added comments in Figma for the "Bulk import" and "download flow".

Mainly,
- can we keep in mind the work we did on this issue (#1423) when it comes to the background task box (users are much more likely to miss information in the bottom-right of the screen and the more we can move messages centre-screen the better)
- I've experienced file imports taking a long time - any more than a few seconds requires a visible progress bar so that the user knows that processing is ongoing and the screen hasn't frozen

**Comment by asminashrestha** [comment]
Hi @emmajclegg We have updated some of the designs in the flow as you have suggested. [View link](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=15482%3A30650&node-id=15962-15178&node-type=frame&viewport=1175%2C-13274%2C0.36&t=Oco6MYo2AeJ6Nit6-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=15650%3A17961&show-proto-sidebar=1) 
Also, We think communicating through figma would be easier for the texts,.

**Comment by emmajclegg** [comment]
Hi @asminashrestha - I've added comments to the "bulk import" Figma, largely around text. I think questions and high-level comments are great on there, but I do think more mundane text review (typos, etc.) would be easiest for me to do by committing changes directly to the GitHub code, for your team to review and merge into the development branch. (I mentioned this on the call with Prawesh and Bibha this morning - it would save both of us time and it's how we would do this kind of task within ODS). Do let me know if that's an option for future?

The same comments will apply to the "within activity" and "no results case" flows - i.e.
- can we make sure page titles are consistent 
- can we make sure "basic activity data", "transactions" and "results" are written consistently throughout (these are the most intuitive way to refer to these three elements of the Standard)
- if sub-text is not providing new information, can we remove it

Any questions, let me know

**Comment by emmajclegg** [comment]
@asminashrestha - following my Figma comment, can I check if this page will still be at the end of the data import flow?

![Image](https://github.com/user-attachments/assets/7a656cfa-249b-4189-8d3a-0ddc37fd9027)

I think this page works well for displaying errors, and it then requires user action to select activities and do the final click to import.

Given that, I don't understand why we need a "click to continue" on this page:

![Image](https://github.com/user-attachments/assets/7d4841a1-3d54-45d5-b764-7255d34171cf)

The user has selected the xlsx data file they want to import, they should be shown on screen that the file is being processed, then - when processing is complete - they should automatically move to the first page above, surely?

**Comment by asminashrestha** [comment]
@emmajclegg Yes, the Add/Update activity page will be at the end of the flow.
![image](https://github.com/user-attachments/assets/8a04664e-3df2-49be-8cb0-e1ec9cd375ed)
Since this is a background process which means that the fetching process will take a long time, therefore, we're trying to give users the freedom to carry on with their other tasks while this is running in the background. So, when this process finishes, we first need the user to know about the process being finished rather than abruptly taking them to the other section that is the list with activities being imported. Hence, we need a 'click to continue' button here so that we can show users a summary of how many errors are present in the imported activity and help them make a conscious decision about moving forward with the process.  After clicking the "Click to continue" users can then move to the "Add/Update activity" page where users can see the full list of errors.

**Comment by emmajclegg** [comment]
Ok, @asminashrestha - for the sake of progressing this, let's keep the ongoing tasks box where it was (bottom-right) and make sure we have a clear "Click to continue" when user action is required. It's hard for me to comment further on messaging at the moment, as the current design draft is talking about publishing data rather than importing.

> Since this is a background process which means that the fetching process will take a long time

Similar to the discussion on bulk publishing (#1480), we do need to set limits and keep the user informed in these cases:
a) how big of a data import file is too big for IATI Publisher to successfully import? (and how do we inform the user of this before they attempt the action)
b) can we be more specific about what a "long time" is in user messaging? e.g. "this may take a few minutes", or "this could take up to x minutes for files larger than y"...

**Comment by PG-Momik** [comment]
@emmajclegg 
> a) how big of a data import file is too big for IATI Publisher to successfully import? (and how do we inform the user of this before they attempt the action)
- We are currently unsure of the maximum file size that IATI Publisher can handle for imports, as we haven't conducted stress tests to determine the capacity for importing large XLSX files.

> b) can we be more specific about what a "long time" is in user messaging? e.g. "this may take a few minutes", or "this could take up to x minutes for files larger than y"...

- In this context, a "long time" refers to any task that takes longer than usual, like when you quickly save a form. For actions that may take a bit longer, we run them in the background so users can continue using the application without being stuck waiting for the task to finish.
- When it comes to user messaging, we can’t specify an exact duration like "this could take up to x minutes for files larger than y" because import times vary based on the payload. Instead, we could use the more general "this may take a few minutes" 

---

We should address the import and publish size limits in a separate issue.  We’ve conducted stress testing for publishing, we haven’t yet done the same for importing files. Focusing on that now would divert us from our current priorities, which are: 1) Successfully publish 100 files and 2) Ensuring an easy and smooth import process. But if it’s absolutely crucial, we’ll prioritize it and find a max limit for imports.

---

cc: @BibhaT @asminashrestha

**Comment by asminashrestha** [comment]
@emmajclegg We have now moved the ongoing tasks box to the bottom right, following your suggestion.

**Comment by emmajclegg** [comment]
@PG-Momik - yes, as discussed, let's not spend a lot of energy investigating the limits of bulk importing at this point. My last comments were related to the workflow and whether we really expect the user to be navigating away from the import screen because of the processing time. Either way, if it becomes an obvious issue during testing, we can revisit it then.

@asminashrestha - do you have all the feedback you need now on the [import workflow design](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=15482%3A30650&node-id=15650-17961&node-type=frame&viewport=1175%2C-13274%2C0.36&t=Oco6MYo2AeJ6Nit6-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=15650%3A17961&show-proto-sidebar=1)? I've no further comments

**Comment by asminashrestha** [comment]
Yes, Thanks @emmajclegg

**Comment by asminashrestha** [comment]
hI @emmajclegg One more thing we wanted to share: Please take a look at this [Error state](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=14921%3A37626&node-id=16357-29423&node-type=frame&viewport=458%2C-2996%2C0.69&t=IuuQutHiIZeHWbdL-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=15062%3A29319). In step three of the onboarding process, users will encounter an error state if they attempt to publish before their email has been verified or if their account has not been verified on the Registry. This is crucial because publishing is not allowed until verification is confirmed. The error message displayed will clearly inform users of this requirement, ensuring they understand the necessary steps to proceed.
