### ISSUE TITLE
Prevent publication of activities that are already published

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1606]
IATI Publisher allows publication of activities that are already published:

![image](https://github.com/user-attachments/assets/08ebe56a-53ae-420b-a96e-bcc435249492)

**User issues:**
- This risks confusing the user about whether their activities are published or not
- As users become able to publish 100 activities at once, we risk creating extra processing work if activities that don't need republishing are accidentally selected for publication.

Can we skip already "published" activities from the publishing process?

**Comment by PG-Momik** [comment]
Hi @emma

> Can we skip already "published" activities from the publishing process?

> [!NOTE]
> In the text below 'Published state' refers to activities that are published and havent been edited (Basically, it doesnt include republish-able activities)

Regarding this, there are 2 possible approaches we could follow:
1. Disable publish button if ANY ONE of the selected activities are already on the published state. 
2. Disable publish button if ALL of the selected activities are already on the published state.

We've crossed out a additional approach that came up in our internal discussion:
1. Disable selection checkbox for activities that are already on the published state.

This is because the checkbox are used for downloading as well. If we were to follow the above suggestion, it'd prevent users from downloading activities that are in the published state

cc: @Yash-ftW @BibhaT

**Comment by emmajclegg** [comment]
> Regarding this, there are 2 possible approaches we could follow:
> 
> 1. Disable publish button if ANY ONE of the selected activities are already on the published state.
> 2. Disable publish button if ALL of the selected activities are already on the published state.

Hi @PG-Momik - Approach 2 above definitely makes sense, as it's logical for a user to not be able to publish in that situation.

If a user selects a mix of activities in the published and unpublished/republish states, even if the user's unaware, I thought it makes sense for IATI Publisher to ignore activities that are already "published" from its data processing. But that's more from a publishing performance point of view and less of a user confusion issue.

**Comment by Sanam-07** [comment]
- [ ] Issue 1 : The disable button does not work when the user cancel the activity publication and select only the published activity.
![image](https://github.com/user-attachments/assets/684e53a3-af1d-46fd-9dab-26fe95ed674c)

**Comment by Yash-ftW** [comment]
@emmajclegg, This has been deployed to staging.
