### ISSUE TITLE
CSV export sometimes missing document-link title and description

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1624]
This relates to this support ticket: https://iati.zendesk.com/agent/tickets/45789

A publisher has flagged to us that some of their activity document titles and descriptions are not appearing in their CSV export. This is despite these titles and descriptions appearing ok in the IATI Publisher interface, published XML file and exported XML file.

**Comment by PG-Momik** [comment]
I 've confirmed the issue mentioned in the zendesk ticket is an intended behaviour. Csv import/export module has not had any recent changed.

### Some context on CSV **IMPORT** first:

In IATI publisher every element that has a narrative subelement has 2 fields: `narrative` field and an associated `language` field. In csv however, there is no `language` cell for a `narrative`. 

![Group 1142813086](https://github.com/user-attachments/assets/8e7b6efe-5cf3-44d7-909c-b9e702229576)


Which is why user are supposed enter the `activity default language` when importing.

![Screenshot from 2024-11-29 11-16-28](https://github.com/user-attachments/assets/6a4ac6f8-6098-4fd6-8f21-11a14fde2fea)


This will map `language` values for the `narrative` values in csv. And the `activity default language` will be accessible here:

![Screenshot from 2024-11-29 11-17-02](https://github.com/user-attachments/assets/3ed0e596-eb69-4558-8f53-ab9aad4016b4)

Given that we try to import multiple narrative's by inserting 2 values in csv like this:

![Pasted image 20241129112421](https://github.com/user-attachments/assets/494b7e6f-4392-4dea-82ab-e9fb123e402a)

We get the following errors:

![Pasted image 20241129112806](https://github.com/user-attachments/assets/ec8876e0-2d06-444d-a89b-152a6124a628)


Unlike XLS we cannot do this in csv:
![Pasted image 20241129112740](https://github.com/user-attachments/assets/a66873f1-dd6f-4c56-a65d-3ed9e24c443c)

This will be treated as 3 `document links`. And not 2 `document links` where the first `document link` has 2 `title narratives`.

### Conclusion:
Narrative filed imports will be mapped to activity default language since separate language values are not available for each narrative.

---

### Zendesk issue

Given the conclusion mentioned above, let us break down the zendesk issue.

The default language for activity mentioned in the ticket (identifier: XM-DAC-701-8-202110179) is 'JA':

![Pasted image 20241129113647](https://github.com/user-attachments/assets/b396cdd9-7760-4d07-876d-2f834cb7ddb7)


This means that when exporting the activity dataset, this language takes precedence over narrative field's associated language. Resulting in only those narratives being downloaded where the associated language is 'JA'. 

![Group 1142813087](https://github.com/user-attachments/assets/0c716d1b-dbae-4985-a540-c2f5796085b7)

This is done so that the file faces no issues when re-importing it.

![Group 1142813088](https://github.com/user-attachments/assets/8b0fc717-9abc-4216-9ee7-6ecb0a35d649)

**Comment by PG-Momik** [comment]
hi @emmajclegg  please have a look at the comment above.

**Comment by emmajclegg** [comment]
Hi @PG-Momik - ok thanks a lot for the detailed feedback. I've gone back to the publisher to check what they're trying to do with their exported data and will suggest a different approach in this case (likely advising that they use the XLS templates instead).

I'll close this issue when I've heard back from them.

**Comment by emmajclegg** [comment]
Closing this issue as there's been no further questions from the publisher. They succeeded in exporting and editing their data via the XLSX download.
