### ISSUE TITLE
Import .CSV/.XML file

### ISSUE THREAD

**Issue by nirvanalama** [younginnovations/iatipublisher#437]
Here is the link. Let us know if you have any feedbacks.
@k8hughes @titiolukole @praweshsth @Rohini-IATI @DaveEade49 

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=9741%3A168487&node-id=9742%3A168488&viewport=542%2C294%2C0.05&scaling=min-zoom&starting-point-node-id=9742%3A168488

**Comment by nirvanalama** [comment]
@Sanilblank

**Comment by DaveEade49** [comment]
Hi, 
1. on the page where the upload has identified two errors ( for 4206 and 4113 ) - is there a way to see what the errors and to correct them?
2. On that same page 4113 is in **bold** whereas 4206 is not - is there any significance to this?
3. On page 9 "Your Activities" after the successful import the activities which have been imported don't show - is this just because it's a "Mock Up"?
4. On the "Your Activities" page the activity title is shown, but the references on previous pages ( things like 4206-OSBP ) are not - is there any reasoning behind this?

Thanks
Dave

**Comment by nirvanalama** [comment]
Hello,

### 1. on the page where the upload has identified two errors ( for 4206 and 4113 ) - is there a way to see what the errors and to correct them?
**- You can click on the (show 2 errors) to expand. As, the activities are being imported we cannot let the users to correct the errors. But they can go back to the .cvl/.xml file and correct it there instead.**

### 2. On that same page 4113 is in bold whereas 4206 is not - is there any significance to this?
**- That was design error and has been fixed. Thanks for pointing out.**

### 3. On page 9 "Your Activities" after the successful import the activities which have been imported don't show - is this just because it's a "Mock Up"?
**- As the design is just a prototype we are not able to show the changes but on the system 'Your Activity' page will update.**

### 4. On the "Your Activities" page the activity title is shown, but the references on previous pages ( things like 4206-OSBP ) are not - is there any reasoning behind this?
**- Our Team member will get back to you on this issue.** @man-git007 @praweshsth @Sanilblank 


@praweshsth @DaveEade49
