### ISSUE TITLE
Bug :More publishing issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#483]
Context
- Desktop
- Chrome 103.0.5060.114

Preconditions
- Username: Ram
- Password: 12345678
- https://stage.iatipublisher.yipl.com.np/

- [ ]  #**Issue 1: publishing/unpublishing/republishing process is not smooth.**
Actual Result
https://user-images.githubusercontent.com/78422663/189644446-9feb8fd7-35b6-4b6c-8fb3-8cc05207334e.mp4
Expected Result
- Should be smooth 
- [x] **Issue 2: The default value hasn't been displayed on IATI Datacenter** 
Actual Result
https://user-images.githubusercontent.com/78422663/189644056-5fa6a4ce-48bf-400b-9de4-6bfb67b1941a.mp4
Excepted Result
- Should be displayed on IATI Datacenter 
- [x] **Issue 3: policy marker (vocabulary)  and planned-disbursement (Receiver org,@receiver-activity-id) haven't been displayed on IATI Datacenter.**
Actual Result
![Screenshot from 2022-09-12 17-27-22](https://user-images.githubusercontent.com/78422663/189645860-082e288c-f407-4a0d-8333-6bf7ccf16d64.png)
![Screenshot from 2022-09-12 17-28-19](https://user-images.githubusercontent.com/78422663/189645903-53b1afb0-4082-4dfc-babe-5dca4b71a371.png)
Excepted Result
- Should be displayed on IATI Datacenter 
- [x] **Issue 4: Bad user experience** 
Actual Result
https://user-images.githubusercontent.com/78422663/189647757-838595cc-ca47-41ca-8e03-f16044bd77bf.mp4
Expected Result
- Clicking different buttons should be disabled while publishing the data 
- [x] **Issue 5 : Static popup**
Actual Result
https://user-images.githubusercontent.com/78422663/189641295-a1a0ecfb-374e-4e1e-bcb6-69f6dac46127.mp4
Expected Result
- Should be dynamic 
- [x] **Issue 6: Static validation**
Actual Result
https://user-images.githubusercontent.com/78422663/189648147-a40a540b-a82b-4520-805e-5b29c3c3adab.mp4
Expected Result
- Should be dynamic

**Comment by man-git007** [comment]
@Sanilblank What is the status of this issue?

**Comment by Sanilblank** [comment]
@man-git007 Will look into this issue soon

**Comment by Sanilblank** [comment]
Regarding issue no 1. The process seems somewhat not smooth because the page is reloaded after completion of publishing and publishing. This had to be done as making the publish, republish, unpublish buttons dynamic on the activities list page seemed difficult without reloading the page. For maintaining consistency in the code, similar process was applied for activity detail page. If needed we can still change this and try to make the process smoother. @man-git007 @SauravSilwal10 

Regarding issue 4, @jenishshrestha could you please look into it since it seems like a FE issue

Regarding issue 2, it is working as intended, the default values of an activity are set when the activity is created, changing the default values in settings will not affect the already created activities default values. @SauravSilwal10

**Comment by man-git007** [comment]
@SauravSilwal10 What is the status of this issue?

cc @Sanilblank

**Comment by jenishshrestha** [comment]
Issue 4 has been solved in branch 533-override-activity-default-values.
Same issue #526

**Comment by SauravSilwal10** [comment]
For issue 1 please refer to backlog issue
