### ISSUE TITLE
Feedback from Prawesh

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#511]
- [x] 1. In settings, ‘Budget Not Provided’ need not be mandatory and doesn’t contribute in completion of settings. Now, when the field is empty, the system tells users that settings is not complete.
- [x] 2. For Budget Not Provided, put the hover over text ‘A code indicating the reason why this activity does not contain any iati-activity/budget elements. The attribute MUST only be used when no budget elements are present.’
- [x] 3. For published activity, don't show the delete button. Show the delete button only for the activities, which are not published.  
- [ ] 4. If the default values are not complete, user should not be able to publish the activity or organisation
- [ ] 5. Organisation detail page, doesn’t show which elements are mandatory in the side menu, detail page and edit form
- [ ] 6. In any form, there is a hover over beside the *mandatory fields, it doesn’t contain any information. 
- [x] 7. While publishing a single activity, the loader for validation shows ‘Validating Activities’. It should be ‘Validating Activity’
- [ ] 8. After validation, the summary of error shows 1 critical errors, 2 errors and 2 warnings, but in the list of of errors in activity detail page, it shows 6 errors. 
- [ ] 9. After unpublishing activity, do we need to show ‘Previously Published on IATI’ in activity detail page and activity list page?
- [x] 10. In organisation file, default values from setting is not filled when saved. 
- [ ] 11. In organisation file's add/edit form, the mandatory sub-element symbol blue star is not shown.

**Comment by praweshsth** [comment]
1,2 - @sriza 
3 - @jenishshrestha 
4 - @jenishshrestha 
5 - @jenishshrestha 
6 - @jenishshrestha

**Comment by praweshsth** [comment]
@Sanilblank take a look at these too.

**Comment by Sanilblank** [comment]
@praweshsth Regarding Issue 4
As of now, the system has no way of changing the default values of activity so according to your suggestion, if a user creates activity without completing the settings default values, the user will never be able to publish the activity.
Maybe it would be better if we actually did not let them create an activity unless the settings default values are completed.

**Comment by jenishshrestha** [comment]
Issue 3 and 7 completed and pushed.
Issue 5 was completed in code-and-bug-fixes branch.

**Comment by Sanilblank** [comment]
@praweshsth Regarding issues
Issues 1,2,10 have been solved
Issue 8:
The current API of the iati validator responds with 1 in critical issues when there are one or more critical issues present so the count is being shown as 1 in our UI. But according to the document shared by them stating the upgrade to their validator system attached below, starting from 1st October, the critical errors will be returning the actual count of the critical errors. Because of this I don't think we need to change anything within the system.

Issue 9: I think this is a matter of discussion but in my view, I don't see any harm in displaying the message on both pages.
Issue 11: The blue is shown when I am scrolling through the forms or maybe I am not understanding the issue here. @sriza may have to have a look at this issue
Issue 5: In think this needs discussion
