### ISSUE TITLE
UI feedback issues

### ISSUE THREAD

**Issue by titungdup** [younginnovations/iatipublisher#697]
- [x] hover text overlapped by 'save and exit' label in `iati-identifier` page
- [x] Change: “Fill all elements to get 100% score” to “Complete all core elements to get 100% score” in `Publishing progress`
- [ ] ~~Proper hover text format - Done by Abi~~
- [x] Active menu highlight 
- [x] Replace "more" with "additional" on all pages
- [ ] ~~On all element pages, please change “Save and Exit” with “Save” as exit implies that you are leaving the tool.~~
- [x] Change "what is an activity?" text to
"You need to provide data about your organisation’s development and humanitarian ‘activities’. The unit of work described by an ‘activity’ is determined by the organisation that is publishing the data. For example, an activity could be a donor government providing US$ 50 million to a recipient country’s government to implement basic education over 5 years. Or an activity could be an NGO spending US$ 500,000 to deliver clean drinking water to 1000 households over 6 months.  
Therefore your organisation will need to determine how it will divide its work internally into activities. Read the Publishing Checklist(link to publishing checklist page) for more information."
- [x] On the page that provides information about what data has been published please replace “not available” with “missing”
- [x] Change `publishing progress` help text to "The IATI Standard contains a wide range of data elements and your organisation is encouraged to (at least) publish data in elements marked as “Core”."
- [x] Change `publishing progress elements` help text to "Each ‘Element’ represents a basic unit of information in the IATI Standard. Click on each element listed below and complete all data fields contained in the element. For each element, you will find its technical definition, which is labelled as “IATI Standard Reference” and helpful guidance on the data you are required to provide."
- [x] Change `publishing progress Core` help text to "Core elements include the IATI Standard’s "mandatory and recommended" elements and it is important to provide this data to ensure your data is usable and useful."
- [ ] ~~Why is the Organisation Data file “Untitled” - see below. There is no ‘title’ element in the Org-file. Perhaps just change “Untitled” to “Organisation Data”~~

- [x] ~~Contact Email - it appears that this is only accessible when you log out of the system and on the Login Page. This should be available throughout the site/footer should be available in activity detail and activity listing page.~~
- [x] mandatory elements should be changed into core element
- [x] Please this label from all pages
![Screenshot from 2022-11-07 10-10-50](https://user-images.githubusercontent.com/78422663/200226361-93ec5669-367c-43df-b7a2-30b13ac47903.png)

**Comment by SauravSilwal10** [comment]
@titungdup  Issue found this fixes 

- [ ]  Publishing Checklist is not clickable 

https://user-images.githubusercontent.com/78422663/201032607-125c318a-e58d-4942-bbc2-88a4f2b49ef7.mp4


- [ ] In transactions please change recommended element into core.
![Screenshot from 2022-11-10 13-31-10](https://user-images.githubusercontent.com/78422663/201032555-ec96f3ca-f9ef-4381-afe2-fb2c82f062db.png)

- [ ] Highlight menu is missing in import activity 

https://user-images.githubusercontent.com/78422663/201032659-c9bed9cd-4d98-4ba0-8639-22d6fdf1e9ec.mp4

**Comment by SauravSilwal10** [comment]
@titungdup  these are issues left in this fixes 

- [ ] Issue 1: country-budget-items 
### Actual Result 


![Image](https://user-images.githubusercontent.com/78422663/201833072-d5fdffa3-c85c-4d77-8f61-02b45a3de8ed.png)

### Expected Result



![Image](https://user-images.githubusercontent.com/78422663/201833767-d45cd454-780e-472f-897c-763cc195627b.png)

- [ ] Issue 2: Related activity
### Actual Result 


![Image](https://user-images.githubusercontent.com/78422663/201834539-32f93083-cfb3-4009-b741-f491081193ee.png)


### Expected Result


![Image](https://user-images.githubusercontent.com/78422663/201834638-ac7eaa1f-b566-4e5f-9973-c65088f82b6a.png)

- [ ] Issue 3: Transaction, result, indicator replace the half moon with the core element.


![Image](https://user-images.githubusercontent.com/78422663/201835878-56b8a756-ef34-4c49-9fff-9d4b4791e567.png)



![Image](https://user-images.githubusercontent.com/78422663/201835895-47d4de87-bb6a-4a9d-a85f-d3147f9df688.png)

- [ ] Issue 4: Edit Form has not been moved to the left and hover did not display on right.


![Image](https://user-images.githubusercontent.com/78422663/201836402-b4aa3e91-6494-418c-9720-93577494809f.png)



![Image](https://user-images.githubusercontent.com/78422663/201836414-d82c36e6-0fad-49ec-8441-fee6650509f6.png)


 

- [ ] Issue 5: In contact-info, there should be Missing instead of Not Available.


![Image](https://user-images.githubusercontent.com/78422663/201836862-2b48bd79-2a64-494b-9f87-00810b08af9c.png)

**Comment by titungdup** [comment]
Remaining issue 
- [ ] Contact Email - it appears that this is only accessible when you log out of the system and on the Login Page. This should be available throughout the site/footer should be available in activity detail and activity listing page.

**Comment by SauravSilwal10** [comment]
@titungdup Issue found in this fixes 

- [ ] Issue 1: The contact email isn't clickable. 


https://user-images.githubusercontent.com/78422663/202389607-a1bfa10e-74fa-4736-9143-c0c941c21906.mp4


- [ ] Issue 2:  Static page link should display on the next tab.


https://user-images.githubusercontent.com/78422663/202390386-81ea4f38-3cdb-449e-b2e9-f67ecee81ce5.mp4


- [ ] Issue 3: The link doesn't match a comment from the IATI technical team.

Please refer to the comment on this document(https://docs.google.com/document/d/1vcoH50WidT2SNOPKo5jv3qg0NP7DX1Or5qv_uNXwNDw/edit?pli=1)

- [ ] Issue 4: when a user is logged in to the system, Does the dashboard link makes any sense?



![Image](https://user-images.githubusercontent.com/78422663/202390815-325b2980-f38a-4cb9-aea8-d0dd3fbcac88.png)

**Comment by titungdup** [comment]
@SauravSilwal10 
**Issue 1:**
The link won't open anything if the user doesn't have a mail client installed on their device. You need to have a mail client installed.

**Issue 2:**
If we open the footer link pages on a new tab, the link of that new tab will again open a new tab. So it is better to open the static pages on the same tab.

**Issue 4:**
Yes, when a logged-in user navigates to other static pages it's good to have a dashboard link on the footer.
