### ISSUE TITLE
Issue in Download CSV

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#886]
- [x] **Issue 1: Title is not displaying on the Downloaded file**

https://user-images.githubusercontent.com/78422663/208586463-9a5f9ce1-699a-428d-889c-5247d31ef7be.mp4

- [x] **Issue 2:  When the user enters language with the narrative field, the narrative is not displayed on the downloaded CSV** 

https://user-images.githubusercontent.com/78422663/208592428-1d0a91c7-d203-464d-858f-78df9df49c0b.mp4

- [x] **Issue 3: Description is missing** 

https://user-images.githubusercontent.com/78422663/208593297-c591c829-5488-4919-b967-8b2a0c29e480.mp4

- [ ] **Issue 4: Should rethink about recipient region approach, when the user downloads the file from our system and uploads it an  error message is displayed.** 

https://user-images.githubusercontent.com/78422663/208633794-08b887c5-b050-426b-a126-6d12020c4484.mp4

- [ ] **Issue 5: Download button should be present on the activity detail page which makes it easy for the user.**

- [ ] **Issue 6: When a user clicks the download button, is autorefresh possible?**
- [x] **Issue 7: When the user adds two values in a subelement like narrative, description, or category, these values are missing in the Downloaded CSV.**

**Comment by Sanilblank** [comment]
Issue 1,2,3,7: When a user enters the fields in a language other than the default lang, they are not downloaded. This is intentional as the CSV file has only one place to put the lang, which is the default lang. So, if the title or other is downloaded in lang other than default lang, the CSV file will be incorrect as the lang will not be correct. This was previously discussed with @praweshsth dai as well.

Issue 5,6: @rajkarnikar11 please look into these. If the download feature is required in the detail page, the same API can be used for the work. @praweshsth @man-git007 Please confirm if we need to make the recommended update.

**Comment by Sanilblank** [comment]
Issue 5 and 6: We have reached a decision that these are not required as of now.
@SauravSilwal10

**Comment by praweshsth** [comment]
manually closed
