### ISSUE TITLE
Validation Issue During New Registration.

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#897]
![Screenshot from 2022-12-21 17-48-24](https://user-images.githubusercontent.com/72198302/209278844-c032e29e-5519-44e9-85eb-4e488743c2f8.png)
![Screenshot from 2022-12-21 17-49-04](https://user-images.githubusercontent.com/72198302/209278863-1a018104-a408-4c5b-bc00-4ad8d24d720d.png)
- [ ] During New Registration there is new validations which has to be looked over.
- [ ]  And also even if all the steps are not completed the new registration is already successful.

**Comment by sriza** [comment]
The IATI registry publisher registration form has a new validation in the 'website' field inside contact information. This validation requires the website entered to be a file of type 'XML'.

![image](https://user-images.githubusercontent.com/24825118/210304430-aeaf6c1e-bf7f-494f-8cae-7787daecfd6d.png)

Since this validation is not present on IATI Publisher, we are having trouble creating a new publisher. We can successfully create a new user and assign the user with an API token, but the validation error occurs while creating a new publisher.

Could we please verify if the validation is correct on the IATI Registry?
If the validation is correct, could we also be provided with the format of value that the website expects?

cc @praweshsth
